# See values.schema.json for schema description

dss:
  image: docker.io/interuss/dss:v0.15.0 # See https://hub.docker.com/r/interuss/dss/tags for official image releases.
  # When running local images in minikube, uncomment the following line
  # imagePullPolicy: Never
  # Unique identifier for the AWS networking component
#  gatewayId: 6f1e5814-
  conf:
    pubKeys:
      - /test-certs/auth2.pem
    jwksEndpoint: ''
    jwksKeyIds: []
    hostname: dss.example.com
    enableScd: true

cockroachdb:
  enabled: true
  # See https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/values.yaml
  image:
    tag: v24.1.3
  fullnameOverride: dss-cockroachdb
  conf:
    join: []
    # Used to generate a unique identifier for the AWS networking component
    # crdbNodeSuffix: dallas
    cluster-name: interuss-example
    single-node: false
    locality: zone=interuss-example-google-ew1

  statefulset:
    replicas: 3 # Must match the number of .loadBalancers.cockroachdbNodes items.
    args:  # Remove this whole block for minikube
      - --locality-advertise-addr=zone=interuss-example-google-ew1@$(hostname -f)
      - --advertise-addr=${HOSTNAME##*-}.db.example.com
    updateStrategy:
      rollingUpdate:
        partition: 0 # Used for migrations. See /deploy/MIGRATIONS.md#helm-deployment-notes

  storage:
    persistentVolume:
      storageClass: standard

yugabyte:
  enabled: false
  # See https://github.com/yugabyte/charts/blob/master/stable/yugabyte/values.yaml
  Image:
    tag: 2.25.1.0-b381
  nameOverride: dss-yugabyte

loadBalancers:
  cockroachdbNodes:
    - ip: 192.168.0.21
#      subnet: subnet-xxx # for aws only
    - ip: 192.168.0.22
#      subnet: subnet-xxx # for aws only
    - ip: 192.168.0.23
#      subnet: subnet-xxx # for aws only
  dssGateway:
    ip: 192.168.0.10
#    subnet: subnet-xxx # for aws only
#    certName: arn:xxxx # for aws only

global:
  cloudProvider: google
