steps:
- id: 'Setup: Pull Dependencies'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'tidy']
  volumes:
  - name: 'go-vol'
    path: '/go'
- id: 'Lint: Formatting'
  name: golangci/golangci-lint:v1.50.1
  args: ['golangci-lint', 'run', '--timeout', '5m', '--skip-files', '.*\.gen\.go', '-v', '-E', 'gofmt,bodyclose,rowserrcheck,misspell,golint,staticcheck,vet']
  volumes:
  - name: 'go-vol'
    path: '/go'
- id: 'Test: 10x with Race Detection and Coverage'
  name: golang
  env: ['GO111MODULE=on']
  args: ['go', 'test', './...', '-race', '-test.count', '10', '-cover']
- id: 'Evaluate examples/minimum'
  name: 'grafana/tanka'
  args:
  - 'show'
  - '--dangerous-allow-redirect'
  - 'build/deploy/examples/minimum'
- id: 'Evaluate examples/schema_manager'
  name: 'grafana/tanka'
  args:
  - 'show'
  - '--dangerous-allow-redirect'
  - 'build/deploy/examples/schema_manager'
